name: get-latest-data

on:
  workflow_dispatch:
  schedule:
    # 毎日21:10分に実行
    - cron: '10 12 * * *'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: fetch
        run: |
          pip install -q -r requirements.txt
          python3 getdata.py
      - name: commit and push
        run: |
          git config --global user.email "workflow@example.com"
          git config --global user.name "workflow user"
          git add data/graph_data.csv
          git commit -m 'update data' && git push ${REPO} HEAD:${{github.event.pull_request.head.ref}} || true
          git push